version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
  - dependency-name: docutils
    versions:
    - "0.17"
  - dependency-name: sphinx
    versions:
    - 3.4.3
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: pytest
    versions:
    - 6.2.2
  - dependency-name: pytest-mock
    versions:
    - 3.5.1
